Gradient background Generator Project Added
arpit456jain/Amazing-Js-Projects pull request #361
Opened 2022-03-12 10:56 UTC by mrkc2303

# Description

I have made and added the Basic Gradient Background Generator Codebase to the Repository. 

Fixes #354 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:

- Operating system: WINDOWS, MAC
- Text-editors used: VS-CODE

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

<img width="1512" alt="Screenshot 2022-03-12 at 4 21 24 PM" src="https://user-images.githubusercontent.com/67221487/158015290-f3358e90-e71e-4d80-bc02-e0fdafc28508.png">

<img width="1511" alt="Screenshot 2022-03-12 at 4 21 14 PM" src="https://user-images.githubusercontent.com/67221487/158015280-479e664e-1158-4b1f-8174-8a66d222aa1f.png">

2022-03-13 16:46 UTC, VidhiBhatt01 requested changes
![image](https://user-images.githubusercontent.com/83345228/158069952-fb17649f-51c0-4e7a-8bee-d1031cfaa991.png)

Can you please align all the content in the center and make the buttons to select the colors bigger?

2022-03-15 11:24 UTC, VidhiBhatt01 reviewed
It's still the same as before, can't see the changes getting applied.

https://deploy-preview-361--amazing-js-projects.netlify.app/gradient_background_generator/

2022-03-15 12:47 UTC, mrkc2303 commented
Hey @VidhiBhatt01 

I have done the mentioned changes. Kindly check if you need any other. Sorry for the Delay

Thanks

2022-03-17 20:19 UTC, astha2412 approved these changes

2022-03-18 11:21 UTC, merged