Login  animated form
arpit456jain/Amazing-Js-Projects pull request #548
Opened 2022-04-25 18:24 UTC by mayank-del

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #(issue no.)

## Type of change

awesome animated form uses TweenMax library to create cute animated responding Bear in login form

# Checklist:

- [x ] I have made this from my own
- [ x] I have taken help from some online resourses 
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

2022-04-26 11:56 UTC, VidhiBhatt01 requested changes
Remove Background color changer files from this PR. Also, did you make it on your own? If yes, tell the truth rn. I have found similar code somewhere else

2022-04-26 15:21 UTC, mayank-del commented
I have learnt from u tube, obviously, such complex javascript are difficult for me to make without help of internet

2022-04-27 13:25 UTC, VidhiBhatt01 approved these changes

2022-04-27 13:25 UTC, VidhiBhatt01 requested changes
Wait, you need to resolve the merge conflicts too

2022-04-28 11:25 UTC, VidhiBhatt01 approved these changes

2022-04-28 14:24 UTC, merged