Update Home Page UI
arpit456jain/Amazing-Js-Projects pull request #55
Opened 2021-07-26 19:07 UTC by jigar-sable

# Description

Card design update with preview image of each templates. Added hover effects.

Fixes #52 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

2021-07-26 19:10 UTC, jigar-sable commented
@arpit456jain Not added Calculator previews as it will be on different page and will have another script code for fetching.

2021-07-26 19:15 UTC, arpit456jain commented
> @arpit456jain Not added Calculator previews as it will be on different page and will have another script code for fetching.

Ok no problem @jigar-sable  so would you like to work on that in a separate issue??

2021-07-27 02:53 UTC, ankitapuri commented
> @arpit456jain Not added Calculator previews as it will be on different page and will have another script code for fetching.
@jigar-sable then you will redirect the calcutor to another page after clicking on view ?

2021-07-27 04:34 UTC, jigar-sable commented
@ankitapuri all calculators will not be there on the home page, it will have navbar. Calculators are displayed on another page which will have separate JS & JSON file. Someone is working on that issue #46

2021-07-27 05:12 UTC, arpit456jain requested changes

2021-07-27 05:12 UTC, arpit456jain commented on .vscode/settings.json
> +}
@jigar-sable please delete this file

2021-07-27 05:17 UTC, jigar-sable commented on .vscode/settings.json
> +}
Done.

2021-07-27 05:18 UTC, arpit456jain approved these changes

2021-07-27 05:25 UTC, ankitapuri approved these changes

2021-07-27 05:25 UTC, ankitapuri commented
@arpit456jain u can merge

2021-07-27 05:32 UTC, merged