Update main.js
arpit456jain/Amazing-Js-Projects pull request #556
Opened 2022-04-27 08:42 UTC by Qamberhasnain

# Description

As **Underweight** category was also having *yellow* color and *orange* color is more like warning than *yellow*.

- [X] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [X] I have made this from my own
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] My changes generate no new warnings

2022-04-27 13:23 UTC, VidhiBhatt01 requested changes
Link issue number in PR description. Also, add the index.html file so that I can verify the changes

2022-04-28 11:34 UTC, VidhiBhatt01 requested changes
Add index.html file of this project

2022-04-28 11:35 UTC, VidhiBhatt01 commented
Also, you need to link the issue, you have linked PR

2022-04-28 11:54 UTC, Qamberhasnain commented
> Also, you need to link the issue, you have linked PR

I have linked the issue.

2022-04-28 11:58 UTC, Qamberhasnain commented
> Add index.html file of this project

There is no need for index.html as I just made changes in main.js. And I don't have the original files as I did not create this repository. I just made necessary changes. If you still wish to see index.html file, please [Click Here](https://github.com/arpit456jain/Amazing-Js-Projects/blob/master/BMI-Calculator/index.html)

2022-04-28 14:38 UTC, merged