Spy number checker
arpit456jain/Amazing-Js-Projects pull request #596
Opened 2022-05-02 14:54 UTC by eswarbhageerath

This PR fixes the issue Spy Number Checker #588.
Kindly review it.

2022-05-03 10:08 UTC, VidhiBhatt01 requested changes
Did you totally make this on your own? If not add the resources you used in a readme file. Also, if you have raised this issue in any other repo then please close this PR

Lastly, add this project in style_links.json

2022-05-03 10:08 UTC, VidhiBhatt01 commented
https://deploy-preview-596--amazing-js-projects.netlify.app/spy%20number%20checker/

2022-05-03 10:37 UTC, eswarbhageerath commented
@VidhiBhatt01  I made this totally on my own, I did not raise this issue in any other repos, I have added this project in style_links.json

2022-05-04 18:49 UTC, VidhiBhatt01 approved these changes

2022-05-05 10:09 UTC, merged