Eyesightcheck
arpit456jain/Amazing-Js-Projects pull request #620
Opened 2022-05-04 21:26 UTC by DragonUncaged

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #680 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
![preview](https://user-images.githubusercontent.com/72241207/166506995-a902d4ba-e321-42fb-b005-e8c2f984395c.png)

2022-05-05 17:01 UTC, VidhiBhatt01 requested changes
In small screen sizes, I can't read what this button says. Fix it please. Also it would be great if you can add a readme file and explain in brief about how this project works.

![image](https://user-images.githubusercontent.com/83345228/166974931-4b12dbd0-e755-42f3-9b94-9b02ab3ab025.png)

2022-05-05 17:01 UTC, VidhiBhatt01 commented
https://deploy-preview-620--amazing-js-projects.netlify.app/eyesight%20check/

2022-05-06 11:11 UTC, DEEPALI-SUK requested changes
just add one preview.png

2022-05-06 11:25 UTC, DragonUncaged commented
> just add one preview.png

added in readme file

2022-05-07 15:53 UTC, astha2412 approved these changes

2022-05-07 16:19 UTC, arpit456jain commented on style_links.json
> +    "link":"Screen distance Measure/index.html"
wrong name of project

2022-05-07 18:03 UTC, DragonUncaged commented on style_links.json
> +    "link":"Screen distance Measure/index.html"
Done !!.

2022-05-09 13:26 UTC, merged