Added Custom QR Code Generator
arpit456jain/Amazing-Js-Projects pull request #706
Opened 2022-05-22 17:51 UTC by hariketsheth

# Description
- Added a QR Code Geenrator, that generates a custom QR Code for the users based on the URL specified in the script

Fixes:  #705 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
![image](https://user-images.githubusercontent.com/72455881/169708773-f1d1cf3f-4d1e-4326-825f-f6b88c05989a.png)

2022-05-23 04:02 UTC, DEEPALI-SUK requested changes
add in style_links.json of the main repo, see how others have done

2022-05-23 11:14 UTC, VidhiBhatt01 approved these changes

2022-05-23 11:15 UTC, VidhiBhatt01 reviewed
https://deploy-preview-706--amazing-js-projects.netlify.app/custom%20qr%20code/

2022-05-25 08:57 UTC, hariketsheth commented
@arpit456jain Please merge this PR and add labels

2022-05-25 14:35 UTC, merged