Fixed Errors - Refactored Images and Added Fallback
arpit456jain/Amazing-Js-Projects pull request #709
Opened 2022-05-22 18:09 UTC by hariketsheth

Fixes:  #701 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2022-05-23 11:13 UTC, VidhiBhatt01 requested changes
I think there are a lot of unwanted changes/files on this PR. Please look into it. else just re fork the repo and make a new PR

2022-05-23 11:26 UTC, hariketsheth commented
@VidhiBhatt01 - Removed unnecessary files.
Kindly proceed with further review. Also will follow the process told by you from next time
Sorry for the inconvinience

2022-05-24 11:51 UTC, VidhiBhatt01 approved these changes

2022-05-25 08:56 UTC, hariketsheth commented
@arpit456jain Please merge this PR and add labels

2022-05-25 15:48 UTC, merged